
export const WAEI_CAPTURE_SCRIPT = `
(function(){
  var currentQuestionIndex=0, answers={}, finished=false, lastSig="";
  function clean(v){return String(v||"").replace(/correct answer/gi,"").replace(/wrong answer/gi,"").replace(/[✓✔✘✗]/g,"").replace(/\\s+/g," ").trim();}
  function absUrl(src){if(!src)return "";try{return new URL(src,location.href).href}catch(e){return src}}
  function cfg(){try{return window.widgetconfig||{}}catch(e){return {}}}
  function qs(){var c=cfg();return Array.isArray(c.questions)?c.questions:[]}
  function urlToBase64(url,cb){if(!url)return cb(""); if(String(url).startsWith("data:image"))return cb(url); try{fetch(url).then(r=>r.blob()).then(b=>{var fr=new FileReader();fr.onloadend=()=>cb(fr.result||"");fr.onerror=()=>cb("");fr.readAsDataURL(b)}).catch(()=>cb(""))}catch(e){cb("")}}
  function answerObj(raw,el){var text="",image=""; if(typeof raw==="string")text=clean(raw); else if(raw&&typeof raw==="object"){text=clean(raw.text||raw.caption||raw.alttext||raw.label||"");try{if(raw.src)image=raw.src;else if(raw.image)image=raw.image;else if(raw.img&&raw.img.sources&&raw.img.sources[0])image=raw.img.sources[0].src;else if(raw.sources&&raw.sources[0])image=raw.sources[0].src}catch(e){}}
    try{var img=el&&el.querySelector&&el.querySelector("img");if(!image&&img&&img.getAttribute("src"))image=img.getAttribute("src")}catch(e){}
    try{var pic=el&&el.getAttribute&&el.getAttribute("pic");if(!image&&pic)image=pic}catch(e){}
    try{if(!image&&el&&el.querySelectorAll){var all=el.querySelectorAll("*");for(var i=0;i<all.length;i++){var bg=all[i].style&&all[i].style.backgroundImage;if(bg&&bg!=="none"){var m=bg.match(/url\\(["']?([^"')]+)["']?\\)/);if(m&&m[1]){image=m[1];break}}}}}catch(e){}
    if(!text&&el)text=clean(el.innerText||el.textContent||""); return {text:text,image:absUrl(image),rawText:clean(el?el.innerText||el.textContent||"")};}
  function closestAnswer(t){if(!t||!t.closest)return null;try{return t.closest([".pmc-quiz",".tmc-row",".bw-checkbox[value]",".bw-simple-radiobutton[value]","[role='radio'][value]","[role='checkbox'][value]","[value].bw-button","[value].answer","[value].option"].join(","))}catch(e){return null}}
  function isNav(el){var s=clean(el&&(el.innerText||el.textContent||""))+" "+String(el&&el.className||"").toLowerCase()+" "+String(el&&el.id||"").toLowerCase()+" "+String(el&&el.getAttribute&&(el.getAttribute("aria-label")||el.getAttribute("title")||"")||"").toLowerCase();return /next|previous|back|السابق|التالي|submit|finish|check|score|result|انهاء|إنهاء/.test(s)}
  function qContainer(el){if(!el||!el.closest)return null;try{return el.closest([".question",".qt-question",".qti-question",".quiz-question",".question-container",".question-cover",".page","[class*='question']"].join(","))}catch(e){return null}}
  function qText(container){if(!container)return "";try{var c=container.cloneNode(true);Array.prototype.forEach.call(c.querySelectorAll([".tmc-row",".pmc-quiz",".bw-checkbox",".bw-simple-radiobutton","[role='radio']","[role='checkbox']","button",".bw-button",".right-picture",".picture-marker",".cr-marker","[class*='correct']","[class*='wrong']"].join(",")),el=>el.remove());return clean(c.innerText||c.textContent||"")}catch(e){return ""}}
  function elToBase64(el,cb){if(!el||!window.html2canvas)return cb("");try{window.html2canvas(el,{backgroundColor:"#fff",useCORS:true,allowTaint:true,scale:2}).then(c=>{try{cb(c.toDataURL("image/png"))}catch(e){cb("")}}).catch(()=>cb(""))}catch(e){cb("")}}
  function qSnapshot(el,cb){var c=qContainer(el); if(!c)return cb({text:"",image:""}); var t=qText(c); elToBase64(c,b64=>cb({text:t,image:b64}))}
  function optionIndex(el){var q=qs()[currentQuestionIndex]||{}, opts=q.Answers||[], val=el&&el.getAttribute&&el.getAttribute("value"); if(val!=null&&val!==""){var n=Number(val); if(Number.isFinite(n)){if(n>=1&&n<=opts.length)return n-1; return n}} var txt=clean(el.innerText||el.textContent||""); for(var i=0;i<opts.length;i++){var o=answerObj(opts[i],null); if(o.text&&txt.indexOf(o.text)>=0)return i} return 0}
  function record(el){var questions=qs(); if(!questions.length||currentQuestionIndex>=questions.length)return; var q=questions[currentQuestionIndex]||{}, opts=q.Answers||[], idx=optionIndex(el); if(idx<0||idx>=opts.length)idx=0; var ans=answerObj(opts[idx],el); ans.index=idx; ans.visibleText=clean(el.innerText||el.textContent||""); qSnapshot(el,snap=>{if(!window.__waeiQuestionSnapshots)window.__waeiQuestionSnapshots={}; window.__waeiQuestionSnapshots[currentQuestionIndex]=snap; urlToBase64(ans.image,b64=>{if(b64)ans.image=b64; answers[currentQuestionIndex]=[ans]; send(true)})})}
  function nav(target){var el=target&&target.closest?target.closest("button,a,[role='button'],.bw-button,.next,.back"):target;if(!el)return;var blob=clean(el.innerText||el.textContent||"")+" "+String(el.className||"").toLowerCase()+" "+String((el.getAttribute&&(el.getAttribute("title")||el.getAttribute("aria-label")))||"").toLowerCase(); if(/next|التالي|arrow-right|bw-icon-right|bw-icon-next/.test(blob))setTimeout(()=>{if(currentQuestionIndex<qs().length-1)currentQuestionIndex++;send(true)},150); if(/previous|back|السابق|arrow-left|bw-icon-left|bw-icon-back/.test(blob))setTimeout(()=>{if(currentQuestionIndex>0)currentQuestionIndex--;send(true)},150); if(/submit|finish|check|score|result|انهاء|إنهاء/.test(blob)){finished=true;setTimeout(()=>send(true),400);setTimeout(()=>send(true),1000)}}
  function payload(){var questions=qs(); var list=questions.map((q,i)=>{var opts=q.Answers||[], sel=answers[i]||[], correct=[]; if(q.Valid)correct=String(q.Valid).split(/\\s+/).filter(Boolean).map(v=>answerObj(opts[Number(v)-1]||v,null)); var snap=window.__waeiQuestionSnapshots&&window.__waeiQuestionSnapshots[i]; return {questionNumber:i+1,questionText:(snap&&snap.text)||clean(q.Question||""),questionImage:(snap&&snap.image)||"",options:opts.map(o=>answerObj(o,null)),selectedAnswers:sel,correctAnswers:correct,isCorrect:null};}); var answered=Object.keys(answers).filter(k=>answers[k]&&answers[k].length).length,total=questions.length,score=answered; return {type:"WAEI_GAME_LIVE_RESULT",done:finished||answered>=total,score:score,maxScore:total,percentage:total?Math.round(score/total*100):0,answered:answered,totalQuestions:total,answers:list,currentQuestionIndex:currentQuestionIndex,timestamp:Date.now()}}
  function send(force){var p=payload(),sig=JSON.stringify({a:p.answered,s:p.score,c:currentQuestionIndex,answers:answers}); if(!force&&sig===lastSig)return; lastSig=sig; if(window.parent&&window.parent!==window)window.parent.postMessage(p,"*")}
  document.addEventListener("click",e=>{var a=closestAnswer(e.target); if(a&&!isNav(a))record(a); nav(e.target)},true);
  document.addEventListener("change",e=>{var a=closestAnswer(e.target); if(a)record(a)},true);
  setInterval(()=>send(false),1000); window.WAEI_COLLECT_GAME_RESULT=payload; setTimeout(()=>send(true),1000);
})();
`;
